version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: pydash
    versions:
    - 4.9.2
    - 4.9.3
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: isort
    versions:
    - 5.7.0
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: mypy
    versions:
    - "0.800"
