version: 2.1

jobs:
  test:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          key: deps1-<< parameters.version >>-{{ checksum "poetry.lock" }}
      - run:
          name: Install Poetry
          command: pip install poetry
      - run:
          name: Install dependencies
          command: poetry install
      - save_cache:
          key: deps1-<< parameters.version >>-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run Flake8
          command: poetry run flake8
      - run:
          name: Run Python tests
          command: poetry run py.test --cov=./prosemirror/
      - run:
          name: Upload coverage to codecov
          command: poetry run codecov

workflows:
  version: 2
  build:
    jobs:
      - test:
          name: test-py36
          version: "3.6"
      - test:
          name: test-py37
          version: "3.7"
      - test:
          name: test-py38
          version: "3.8"
      - test:
          name: test-py39
          version: "3.9"
      - test:
          name: test-py310
          version: "3.10"
