name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install uv
      - run: uv venv
      - run: uv pip install --requirement pyproject.toml
      - run: uv pip install setuptools setuptools-scm wheel build
      - run: .venv/bin/python -m build --no-isolation
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
